### ISSUE TITLE
actions/cache produces failure given empty hashFiles

### ISSUE THREAD

**Issue by lrworth** [regadas/github-actions-dhall#32]
```dhall
GithubActions.steps.actions/cache
  { path = "my-path", key = "my-key", hashFiles = [] : List Text }
```
produces this job:
```yaml
      - name: my-path cache
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-my-key-${{ hashFiles() }}"
          path: my-path
          restore-keys: |
            ${{ runner.os }}-my-key-
```

but GitHub Actions fails with `Too few parameters supplied: '('` due to `hashFiles()`.
